### ISSUE TITLE
Citations and table of figures/tables disappearing

### ISSUE THREAD

**Issue by aclyde11** [k4rtik/uchicago-dissertation#2]
Hello,
I have been using this template for awhile, and suddenly the references are all broken. I am unsure if this is a problem with overleaf or the template file. When compiled it cannot find not a single reference, and the table list of figures breaks too. 

Not sure how to share this so you can recreate the issue.

**Comment by k4rtik** [comment]
Sorry, unsure if I ever saw this issue.

Is anyone else facing this?

**Comment by k4rtik** [comment]
No response, closing.
