### ISSUE TITLE
Title Page is not to spec as per dissertation office review

### ISSUE THREAD

**Issue by suhailrehman** [k4rtik/uchicago-dissertation#3]
As per an email that i received  from the dissertation office during draft review:

> TITLE PAGE
> 
> -Please add a line space above A DISSERTATION
> 
> -Please add a line space above BY

Attaching a pull request that will fix this issue shortly.

**Comment by k4rtik** [comment]
I am surprised that people are using this template for years and no one noticed this issue. Thanks for pointing out and sending the PR.

**Comment by suhailrehman** [comment]
Happened to me, I thought it was a one-off, but my roommate mentioned today he had the same issue with the office, so I decided to open the PR. Cheers.
