### ISSUE TITLE
Chapter title on blank page

### ISSUE THREAD

**Issue by Sellamize** [k4rtik/uchicago-dissertation#5]
I am using this template for my dissertation and whenever I add a new chapter, it compiles the title of the chapter on its own page, and forces the content to be on the following page. Every chapter starts with the title on an empty page. How do I fix this to have the main text immediately follow the chapter title? 

Thanks!

**Comment by k4rtik** [comment]
I cannot reproduce this. What version of LaTeX are you using?

For reference, I am on:
```
❯ pdflatex --version
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

It is recommended to use a relatively recent version of LaTeX.

**Comment by Sellamize** [comment]
I am on the same version, so I don't think it's due to that.
I checked the .cls file and I honestly have no idea what could be causing this.

**Comment by k4rtik** [comment]
Is it possible for you to share a minimal example that demonstrates the
issue?

**Comment by Sellamize** [comment]
Sorry for the confusion on this. I thought the problem came from a command in the template. 

I found out that I was using the command \include{chapter} for each chapter that was on a separate file, which turns out forces page breaks around the included text. I switched to \input{chapter} and the problem disappeared.

Thanks for your help :)
